.PNONY: pmtest1 pmtest2 pmtest3 pmtest4 pmtest5 pmtest6 pmtest7 clean

pmtest1:
	nasm pmtest1.asm -o pmtest1.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest1.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest2:
	nasm pmtest2.asm -o pmtest2.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest2.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest3:
	nasm pmtest3.asm -o pmtest3.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest3.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest4:
	nasm pmtest4.asm -o pmtest4.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest4.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest5:
	nasm pmtest5.asm -o pmtest5.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest5.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest6:
	nasm pmtest6.asm -o pmtest6.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest6.com /mnt/floppy
	sudo umount /mnt/floppy

pmtest7:
	nasm pmtest7.asm -o pmtest7.com
	sudo mount -o loop pm.img /mnt/floppy
	sudo cp pmtest7.com /mnt/floppy
	sudo umount /mnt/floppy

clean:
	rm *.txt
